### ISSUE TITLE
LLM one-pager

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/svelte.dev#247]

**Comment by didier** [comment]
Some help: https://llmctx.com

**Comment by Rich-Harris** [comment]
Relevant: https://llmstxt.org

Not sure how a root-level `/llms.txt` would handle documentation needs for different packages, and it's annoying that the designers of this 'standard' apparently didn't consider `.well-known`, but it [seems to have some traction](https://directory.llmstxt.cloud/)

**Comment by khromov** [comment]
I forked the llmctx repo and added better support for Svelte docs (including being able to omit 
LEGACY/NOTE/DETAILS block and also publishing a variety of different sizes that fit different context windows.)

Demo:
https://svelte-llm.khromov.se/

Code:
https://github.com/khromov/llmctx
