### ISSUE TITLE
Playground editing can cause scrolling if zoom level is not 100%

### ISSUE THREAD

**Issue by brunnerh** [sveltejs/svelte.dev#483]
Only seems to happen with significant zoom, e.g. 150%.

[Example code](https://svelte-omnisite.vercel.app/playground/hello-world?version=5.0.3#H4sIAAAAAAAACn1VTW_jNhD9KwM2C9uBLTlJsQfaclv0WqCH9hYFWFoa2UQoUiWpjV1B_73ghyXZcVe5mG_mDcl5b5iOVFygIfS1I_bcIKEeIEsiWe1WvzVNYr6jsA7bM4P38EJJi9IaQsnWFJo3dpfL3PK6UdrCH9xYqLSqYZakbhGJs0lOBx-aW7YXCH3MDUmpsUrjbONyCyWNBatKZSAbCPNXF8ttB7yk8LSEEsMZuJIUZkcUQs2WUCqJFComDEK_nFKebykfSovyh5SXW4o78g8ZP98yYg_ucd4W7royt_6qSc30O2RQtbJw3LlDA20BXdjDQYlDIPOBTYAfLr0KPzza53KbjiLJrZen8wm9J2edP0wP6e5-2Oo2RsmSWDxZQj20_B8PTTS_NtF14LOLwEMnm-WkVmUrMCe7XAIMpvmn5dL-2dqLaXISXYPMcHnIyeYqvdDKmIqV-CnfaiYNd-295VSCN5_SmeQ1sxhzgy9fDcpyCRoL5N_xDbJxu3nn0gDKVrMg_8t6vQxYxYTYs-J9LlWJS2iYZrXxwoL_QnFjz8KJe0D7u6qb1mL5l4M8a7G5TvaXqZSuIQvEZIJkGeREKok5gV8gJzkBepvl7RcqarStluNx7l_CfaHldNBkEiqMoTC3C8h28G2E3TfsSeGhGxY9mIIJnD90th9vFz7VsILbs8_vx9C3Yb8-EnqPeP6144ffAHjyMguM78rmBozDdM1vhed2PyErjnG2kooLi3o-Tx8f4Vc3BtB1cbaZPG-g7-Ex9Zv4NkwmNsviMDPjYfATnvByEa-3FWyPAqLpqHNk5oqjYOegwkSUJ7e81QL6fndpz1ZwKAQzhvrtuaTRsq7mO54pxO3dkVVrqfP1ndhu7P2Wy6a1U5lcA7KcFEcs3vfqlJNp0KNYZt3QhH4aVpIWRyYPmHVzHJoV3sH4-GFStFqjtH8zfUCbxIqLSZ10ej7TMLmL242vcL9NfWDoTCp4XGxT3_Ogc-p09u-mV945yM2LDwYN43gM1lwnX6MJ3fO1KrFQF30El7iyR63aw9Hn9GHYWnGpIrixK7_DyrWRggwmdLGa6QOXFNZx3bCy9EpfgA9e2qN3wZdpdcEv1QfGk8b6pupT8jKClZJ2Zfi_6PDnEd-r08ocWak-KKzhpTnB07o5gT7s52twfymsk-fFkK1L1CvNSt4a6tIvx9qmoYvX_0Pe-v8AIhTXGpMIAAA=)

E.g. when I try to edit the animation parameters of line 30 in `List.svelte`:
```svelte
<label animate:flip={{ delay: 300, duration: 100, easing: quintOut }}>
```

Every keystroke sends the scrollbar further down.

[7b937db4-a731-4834-a9c4-bba84b4683a8.webm](https://github.com/user-attachments/assets/26351c13-61b7-4182-83bd-09b449bb1fd4)

Chrome & FF, Windows 10.

**Comment by Rich-Harris** [comment]
closed via #597
