### ISSUE TITLE
docs(omnisite): On mobile the title of menu sections should have background color if sticky

### ISSUE THREAD

**Issue by jnehlmeier** [sveltejs/svelte.dev#514]
### Describe the bug

Without background it looks weird while scrolling the menu and the title being sticky.

<img width="295" alt="mobile-menu-headlines" src="https://github.com/user-attachments/assets/ee1a6adb-6f50-4ba2-8cc2-899ea6cae6e2">

### Reproduction

--

### System Info

```shell
--
```

### Severity

annoyance

**Comment by Rich-Harris** [comment]
closed by #521
