### ISSUE TITLE
docs(omnisite): On mobile the main page is scrollable while menu is opened

### ISSUE THREAD

**Issue by jnehlmeier** [sveltejs/svelte.dev#515]
### Describe the bug

If you open the menu on mobile then you can still scroll the main page behind the opened menu. This results in:

- The footer menu disappears when scrolling down with the menu still being opened. Looks broken
- If the menu itself is scrollable as well, e.g. in the docs section, then sometimes you do not scroll the menu but the main page, which is annoying.

This behavior only seems to happen on the main page and on any docs page. If you open any tutorials page then the menu behaves better.

### Reproduction

--

### System Info

```shell
--
```

### Severity

annoyance

**Comment by cowboycodr** [comment]
#576 solves this and we should be able to close this issue as solved.
