### ISSUE TITLE
REPL: Add Devtools embed using Chii

### ISSUE THREAD

**Issue by Ocean-OS** [sveltejs/svelte.dev#523]
### Describe the problem

Svelte's REPL often lacks in features that let the dev interact with the actual result or read logs. It makes it difficult to read console logs that aren't easily stringifiable values, and impossible if you're using the REPL on a mobile device. It also seems rather clunky for the REPL to say to open Devtools to read the log. 

### Describe the proposed solution

I've noticed in [SolidJS's playground](https://playground.solidjs.com/) that they use [Chii](https://github.com/liriliri/chii) to embed Chrome's Devtools in the REPL. I think adding this feature would add a lot more functionality to the REPL. 

### Importance

nice to have

**Comment by Rich-Harris** [comment]
We investigated this in #1024 but decided against it
