### ISSUE TITLE
Docs: Have separate documentation for Svelte 4

### ISSUE THREAD

**Issue by Ocean-OS** [sveltejs/svelte.dev#524]
### Describe the problem

As more and more people migrate to Svelte 5, there will be plenty more that decide to stay on Svelte 4. These people will need documentation, and it's not the best to just use something like wayback machine (which is currently barely online) to get the older docs, once the omnisite is moved to svelte.dev. 

### Describe the proposed solution

It would be very useful for many people to have a separate part of the new Svelte site to be dedicated to Svelte 4 documentation. This could be implemented in a similar way to React's documentation, where there's separate subdomains for each version, or I could see it being a dropdown in the docs, where you can go to the other version's docs, similar to how [Discord.js's docs](https://discord.js.org/docs/packages/discord.js/14.16.3) are structured. This could also be for more Svelte versions, such as Svelte 2, which [still has a site](https://v2.svelte.dev). 

### Importance

would make my life easier

**Comment by Nicicalu** [comment]
Definitely need a `v4.svelte.dev` until upgrading...

**Comment by josbra-attensi** [comment]
I need this, cannot sadly immediately upgrade - at least the previous major version should be available by the Svelte team officially.

**Comment by ouksal** [comment]
> All the old syntax is available at https://svelte.dev/docs/svelte/legacy-overview
> 
> If that does not suffice please elaborate why

Svelte 4’s documentation was leaps ahead of Svelte 5’s, with detailed explanations that broke down core concepts. I’m not asking for Svelte 4 syntax specifically—I’m asking for that style of documentation that supported developers with clear, thorough guidance. Svelte 5, by contrast, feels like it’s written solely for seasoned developers, overlooking the needs of newer users. For instance, Svelte 4 had a clear section on configuring component events for dispatching custom events. While I understand that in Svelte 5, event handlers are now props and the old dispatch approach is deprecated, a conceptual comparison would still be valuable.

**Comment by sacrosanctic** [comment]
# relevant discord threads

> https://discord.com/channels/457912077277855764/1299158052863475722
> https://discord.com/channels/457912077277855764/1299797670545854534

onboard a new dev to a svelte 4 codebase

> https://discord.com/channels/457912077277855764/1298688591857324194

got rug pulled mid tutorial

> https://discord.com/channels/457912077277855764/1298654059246387250

want a svelte 4 sandbox

**Comment by SteveALee** [comment]
Its not any desire to stay on 4 permentlly, rather many need to get on and cant afford the cost of a migration right now. 

It's cool 4 is just depreciated and we can continue. But we need the docs and tutorial to support that state too.

Plus, the current situation leaves all search engine results invalidated. To some extent that's a fact of life when any site is updated. Until they respider the site.

It appears this is the 3rd hard problem after naming things and cache invalidation. Lol

**Comment by matrs** [comment]
Your code base is not flawless, why you are forcing people to use svelte 5? Is that hard to understand?

**Comment by dummdidumm** [comment]
The old site (with docs and tutorial) is now available at https://v4.svelte.dev/

**Comment by pmalacho-mit** [comment]
Thanks, @dummdidumm !

**Comment by rmunn** [comment]
> The old site (with docs and tutorial) is now available at https://v4.svelte.dev/

Could there be a link somewhere on the new site? I was looking for the Svelte 4 docs just now and I only found this link via a search. It would be nice to have "These are the docs for Svelte 5. If you're looking for the Svelte 4 documentation, it's over [here](https://v4.svelte.dev/)." somewhere near the top of the Svelte 5 docs.

**Comment by TilakMaddy** [comment]
@dummdidumm I need to access docs for svelte v4 server components . Where can I have that ?

**Comment by TilakMaddy** [comment]
Is it possible I can build it locally if you are not interested in hosting it? Please let me know Thanks

**Comment by sacrosanctic** [comment]
> @dummdidumm I need to access docs for svelte v4 server components . Where can I have that ?

@TilakMaddy  https://v4.svelte.dev/docs/server-side-component-api

**Comment by TilakMaddy** [comment]
Nope, I meant I need the whole site that include tutorials for server side!

**Comment by TilakMaddy** [comment]
@sacrosanctic seriously dude ?

**Comment by TilakMaddy** [comment]
The first link to sveltekit in v4.svelte.dev docs introduction is broken.

**Comment by dummdidumm** [comment]
That link pointed to the home page, and the home page for Svelte and SvelteKit is svelte.dev now, so it's correct

**Comment by dummdidumm** [comment]
No, for SvelteKit there haven't been any changes

**Comment by gentunian** [comment]
just in case you ended up here like me:

The "tutorial" orange/red button points to the svelte 5 tutorial. 

The "Tutorial" text link on top right actually points to the v4 tutorial: https://v4.svelte.dev/tutorial/basics

**Comment by Ocean-OS** [comment]
Could the v4 site's REPL link go to the [Svelte 4 REPL](https://svelte.dev/playground?version=4.2.19) instead of the Svelte 5 REPL?

**Comment by jcgl17** [comment]
> No, for SvelteKit there haven't been any changes

This does not seem true. Right now, I'm trying to learn about accessing layout data from +page.svelte. The current docs say things like `import type { PageProps } from './$types';`. As far as I can tell, PageProps doesn't exist in the v4 version of SvelteKit.

Not to mention the various Svelte syntax changes in the examples (e.g. `$props()`).

Am I just dumb, and not understanding how to access layout data from a page in v4 SvelteKit?
