### ISSUE TITLE
Client/server toggle does not work in playground

### ISSUE THREAD

**Issue by matubu** [sveltejs/svelte.dev#525]
### Describe the bug

(It affects <https://svelte-omnisite.vercel.app/playground> and <https://svelte.dev/playground>)

When clicking on the server toggle/radio button, it does not uncheck the client toggle.

[Screencast from 2024-10-22 19-02-23.webm](https://github.com/user-attachments/assets/5a5d358a-a2ca-4792-aa14-0ad9b67e07ed)

### Reproduction

I think this is a minimal reproduction of what is happening:

<https://svelte.dev/playground/hello-world?version=5.0.5#H4sIAAAAAAAAA52QwWrDMBBEf2VZCm7B2HfFDpR8RtWDE28SgbwS0jptMfr3IqU0TUguPexhR9rhzSy4N5YiqrcF5csTqiJgjTxMeXv1voknspK17RDpnr5zLMQSUWEXd8F4WWvWYibvgsDGTd4xscA-uAmqpv1VfiyqVf6ex5KAUBToYYHTYGdSUH24YMcKkuauvdhzdzFe8k2Cdq0ZaxT6FFQSZkr1g1i3BNfh7rw-iJh5lzNxgh6efHA-Pr-sblALX1PypIJu2M8CGa3XGIbROI2wNTyqQ3Cz7_8enHvoNZYeNJaY_3M4krWuOFzX9J6-AUybkbsJAgAA>

Here where its done in svelte playground source <https://github.com/sveltejs/svelte.dev/blob/0c3b93eca055c489bf802cfee197e3ebf19bcb31/packages/repl/src/lib/Output/CompilerOptions.svelte#L13>

### System Info

```shell
Playground
```

### Severity

annoyance

**Comment by Rich-Harris** [comment]
careless bug, but one nice thing: Svelte was actually emitting a warning saying that this wouldn't work, I was just too busy to listen to it

**Comment by matubu** [comment]
haha, great
