### ISSUE TITLE
tutorial: if you switch tabs, the left panel scrolls to the top

### ISSUE THREAD

**Issue by arslivinski** [sveltejs/svelte.dev#528]
Was able to reproduce this on:
- Windows 11 Pro 23H2 Build 22631.4317
  - Firefox 131.0.3 (64-bit)
  - Google Chrome 130.0.6723.59 (Official Build) (64-bit)
  - Microsoft Edge 130.0.2849.46 (Official build) (64-bit)
- macOS Sonoma 14.7
  - Firefox 131.0.3 (aarch64)
  - Google Chrome 130.0.6723.59 (official Build) (arm64)
  - Safari 18.0.1 (19619.1.26.111.11, 19619)

https://github.com/user-attachments/assets/ed65f644-f26f-47fc-ae6f-d366bf79022f

**Comment by Rich-Harris** [comment]
well that's odd
