### ISSUE TITLE
Scrollbar isn't visible (almost)?

### ISSUE THREAD

**Issue by shinebayar-g** [sveltejs/svelte.dev#553]
Can you see it?

![image](https://github.com/user-attachments/assets/2581e524-5dda-43ec-bdd6-4a0684db1b54)

**Comment by cowboycodr** [comment]
It's a _svelte_ scrollbar. I think it's fine, and prefer it over the default Chromium on Windows scrollbar.

**Comment by dummdidumm** [comment]
which OS are you on? I'm on windows and it's thin but not _that_ thin (in fact that's what the CSS does, it sets `--scrollbar-width: thin`

**Comment by shinebayar-g** [comment]
Firefox on Fedora.
