### ISSUE TITLE
learn.svelte.dev and kit.svelte.dev do not redirect properly

### ISSUE THREAD

**Issue by tizu69** [sveltejs/svelte.dev#564]
The two subdomains pre-omni used to be specific to kit and learning svelte. They currently redirect to svelte.dev/; which is fine for kit I'd say, but for learn, that is kinda confusing, especially given old links sent to people do not update :)

**Comment by dummdidumm** [comment]
Could you elaborate? Which old link is not redirecting properly? I just tried out a few and it works correctly

**Comment by tizu69** [comment]
oh yeah no, they do redirect, but to the main https://svelte.dev page - so the connection between learn.svelte.dev and the tutorial gets lost, same for kit

**Comment by dummdidumm** [comment]
the home page of SvelteKit is now shared with the homepage of Svelte, so it's valid to redirect there. Redirecting learn.svelte.dev to svelte.dev/tutorial is a reasonable request
