### ISSUE TITLE
Vim mode

### ISSUE THREAD

**Issue by uglyreptile** [sveltejs/svelte.dev#570]
Any plans to restore vim mode?

**Comment by Rich-Harris** [comment]
yes, just a matter of getting round to it — PRs welcome in the meantime! here's the commented out code dragged over from a much earlier incarnation of the editor — it _may_ be possible to basically just uncomment it (and change `extensions` to `default_extensions`, and also wrap it in an `if (browser)` block), though I'm not certain if the top level await will cause issues with bundling 

https://github.com/sveltejs/svelte.dev/blob/f88b6979a24930c10bc828ab95f4849f0d2090f9/packages/editor/src/lib/Workspace.svelte.ts#L61-L75
