### ISSUE TITLE
Remove `USE_GIT`

### ISSUE THREAD

**Issue by benmccann** [sveltejs/svelte.dev#573]
Why do we need it?

The way I had it setup originally was that if a directory was already present, it wouldn't try to clone the repo again. That would let you symlink in any repos that you wanted to

**Comment by Conduitry** [comment]
If the directory already exists from a previous checkout (and it is not a symlink), then you'd be syncing from old data, right?

What I'd propose instead is to skip the clone only if the appropriate directories are present _and are symlinks_.

**Comment by dummdidumm** [comment]
we need the git command when we eventually setup a github action that auto-syncs stuff

**Comment by benmccann** [comment]
> If the directory already exists from a previous checkout (and it is not a symlink), then you'd be syncing from old data, right?

Then it would do a `git pull`

> we need the git command when we eventually setup a github action that auto-syncs stuff

I'm not proposing to stop using git. Only to remove the use of an environment variable to control whether it is used
