### ISSUE TITLE
https://svelte.dev/tutorial should take you to the first tutorial exercise

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/svelte.dev#574]
I just typed this in manually and got a 404

**Comment by benmccann** [comment]
maybe you had a typo? it takes me to https://svelte.dev/tutorial/svelte/welcome-to-svelte

or I wonder if one of us has a cached redirect or something

**Comment by Conduitry** [comment]
https://svelte.dev/tutorial works for me and is a redirect. https://svelte.dev/tutorial/ is a 404.

**Comment by Rich-Harris** [comment]
ahhhh yeah i had an ending `/`

**Comment by Rich-Harris** [comment]
closing in favour of https://github.com/sveltejs/kit/issues/12869
