### ISSUE TITLE
Tools page or pages?

### ISSUE THREAD

**Issue by benmccann** [sveltejs/svelte.dev#58]
We have a lot of tools. Here are a couple of options for how to display them (ignore the main page content and just look at the sidebar)

Should that create a lot of sections each with mostly a single entry?

![Screenshot from 2024-07-11 14-35-19](https://github.com/user-attachments/assets/64b77854-3ec3-4868-b368-1166ea0f8a19)

Or should we combine them into a single section?

![Screenshot from 2024-07-11 14-55-39](https://github.com/user-attachments/assets/2a2139f9-5741-4f83-bec7-bac2265b6ca8)

A few considerations:
- eslint-plugin-svelte has about 70 pages. It also has an [existing site](https://sveltejs.github.io/eslint-plugin-svelte/) and a playground.
  - Should we try to incorporate the playground into the main site? [Its setup](https://github.com/sveltejs/eslint-plugin-svelte/blob/5d53db1bda21ea7cab53e7618935dc7293f10e9e/docs-svelte-kit/vite.config.mts#L43) looks complicated. I also don't know if that would make things harder for its developers
  - Should we just have a single page with setup instructions and then link to the site?
  - Or should move all the content over except for the playground?
  - I've asked them for their opinion in this issue: https://github.com/sveltejs/eslint-plugin-svelte/issues/824
  - (also note while prototyping that it'd be nice not to make them adopt numeric ordering: https://github.com/sveltejs/eslint-plugin-svelte/issues/825)
- The navigation menu is much simpler if they just have to choose between Svelte, SvelteKit, and Tools. It could be more to digest if there's a double digit number of items (svelte, sveltekit, vite-plugin-svelte, rollup-plugin-svelte, svelte-loader, svelte-preprocess, language tools, prettier-plugin-svelte, eslint-plugin-svelte, etc.)

We can probably add a link to both Svelte and SvelteKit on the homepage (https://github.com/sveltejs/svelte.dev/issues/63) to simplify nav to those two most common destinations, but beyond that you'll have to choose from a larger list in a nav (https://github.com/sveltejs/svelte.dev/issues/61).

**Comment by Rich-Harris** [comment]
let's cross this bridge when we come to it, I don't know that we need to keep an issue open until then. For now I lean towards a section per package — pages are free
