### ISSUE TITLE
[docs] Bad links for deprecations

### ISSUE THREAD

**Issue by adiguba** [sveltejs/svelte.dev#637]
I found some bad links on the page https://svelte.dev/docs/svelte/svelte

In the section **afterUpdate** and **beforeUpdate**, there is a link to https://svelte-5-preview.vercel.app/docs/deprecations#beforeupdate-and-afterupdate
This link is badly redirected to https://svelte.dev/docs/svelte/overview#beforeupdate-and-afterupdate

Same thing in the section **createEventDispatcher** with a link to https://svelte-5-preview.vercel.app/docs/deprecations#createeventdispatcher

There also an invalid link on the word "component events" : https://svelte.dev/docs#template-syntax-component-directives-on-eventname

**Comment by Conduitry** [comment]
These look fixed now.
