### ISSUE TITLE
[DOCS] Small serif text is hard to read on digital displays

### ISSUE THREAD

**Issue by mikestopcontinues** [sveltejs/svelte.dev#639]
### Describe the bug

The docs currently use a serif font for the body text. At small font sizes it's hard to read on digital displays. For headings it's totally readable. (And it would be readable as body text if the default font size was as large as Medium's.)

A sans-serif font would be much more readable.

### Reproduction

![CleanShot 2024-10-25 at 08 45 06@2x](https://github.com/user-attachments/assets/cf802bb2-8460-4c00-8289-c15548a32d66)

### System Info

```shell
N/A
```

### Severity

annoyance

**Comment by Rich-Harris** [comment]
closing as dupe — https://github.com/sveltejs/svelte.dev/issues/517#issuecomment-2438721585
