### ISSUE TITLE
[playground] No error message on compile error

### ISSUE THREAD

**Issue by adiguba** [sveltejs/svelte.dev#641]
When the code has a compile error, the popup "**Error compiling component**" in the preview panel does not contain the error details.
It's only visible on the browser's console.

Example : https://svelte.dev/playground/untitled?version=5.1.2#H4sIAAAAAAAACm2NwQrCMBBEfyXspRfReywFP8KT9VDbLSykm5CMpVL67yZV8OL1zZuZlbSbmCxdFQLHAx1oFMeJ7G0lvELJCsj8a15COKaZHQp7dIn_8d4rWJFnqE59lICm1RYyBR9hVpOcDGw2M0Y_mepTq85Z0fr087UeZDaInSaBeLV7bV8qYg6b_AVeQBbxydt9ewPPZ5fx0QAAAA==

The panel show :
> **Error compiling component**

In previous version we got something like this :
> **Error compiling component**
> Error: ./App.svelte (2:10): "slide" is not exported by "https:// unpkg.com/svelte@5.1.2/src/index-client.js", imported by "./App.svelte".

**Comment by dummdidumm** [comment]
fixed
