### ISSUE TITLE
The copy code button must have cursor: pointer

### ISSUE THREAD

**Issue by K1ender** [sveltejs/svelte.dev#663]
I noticed that the buttons for copying code in the documentation do not have a pointer cursor when hovered over. To enhance user experience and indicate that these buttons are interactive, I suggest changing the cursor style to a pointer when hovering over the copy buttons.

**Comment by dummdidumm** [comment]
Buttons don't have a cursor by default, and it's therefore just fine to not show that icon (in fact it's preferable according to spec to not change that behavior), therefore closing
