### ISSUE TITLE
Strange line in docs then opening search

### ISSUE THREAD

**Issue by K1ender** [sveltejs/svelte.dev#664]
When I scroll to the bottom of the Svelte documentation site (https://svelte.dev/docs), open the search, and then close it, a strange line appears on the page.

But this issue is specific to Firefox, on Chrome this don't work

**Comment by PixelSoftwareStudios** [comment]
Attaching screenshot to show what problem looks like and confirm reproducibility 
<img width="1278" alt="Screenshot 2024-10-27 at 12 20 55 PM" src="https://github.com/user-attachments/assets/03931f08-610b-4f82-92e8-192659a2282b">
