### ISSUE TITLE
No menu at certain viewport widths

### ISSUE THREAD

**Issue by arichardsmith** [sveltejs/svelte.dev#676]
In the docs, there is a small interval (~32px) where the mobile menu on the bottom is hidden, but the sidebar isn't shown yet. This leaves clicking through page by page as the only way to navigate. To make it worse, an iPad Air in portrait mode happens to fall exactly in this dead spot!

I might be getting which-component-renders-what wrong, but it looks like the mobile menu (from [`packages/site-kit`](https://github.com/sveltejs/svelte.dev/blob/70aaaab5fcdc81751167982cff0e40272c5f97d6/packages/site-kit/src/lib/nav/Nav.svelte)?) nav gets hidden at `800px`, while the sidebar ([docs layout component](https://github.com/sveltejs/svelte.dev/blob/70aaaab5fcdc81751167982cff0e40272c5f97d6/apps/svelte.dev/src/routes/docs/%5B...path%5D/%2Blayout.svelte)?) is hidden until `832px`.

I'm happy to try to fix it and submit a PR. I guess you'd want to keep the mobile nav until `832px`? That would be a smaller change than making the sidebar appear from `800px`. But is `site-kit` being used elsewhere?

**Comment by Rich-Harris** [comment]
This was coincidentally fixed in #679, before I saw this issue! Thanks for the report

**Comment by arichardsmith** [comment]
Awesome, thank you! Back to perusing the new docs on my iPad.
