### ISSUE TITLE
Redirects are not done on /docs/svelte & /docs/kit

### ISSUE THREAD

**Issue by Devr-pro** [sveltejs/svelte.dev#720]
Currently `/docs/svelte` and `/docs/kit` returns 404
pages should be redirected to their appropriate routes : 
Redirect `/docs/svelte` to` /docs/svelte/overview` & `/docs/kit` to `/docs/kit/overview`

**Comment by Rich-Harris** [comment]
`/docs/svelte` and `/docs/kit` _do_ redirect. The issue is that `/docs/svelte/` and `/docs/kit/` don't. This is a bug in SvelteKit https://github.com/sveltejs/kit/issues/12869

**Comment by Devr-pro** [comment]
Oh, missed that one
