### ISSUE TITLE
Deleting a filename in the playground breaks stuff

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/svelte.dev#763]
The layout goes wacky...

<img width="173" alt="image" src="https://github.com/user-attachments/assets/fcba1228-bc17-499d-924c-6a6755682644">

...and you can't subsequently edit the name. Blurring an empty input should probably either mean 'no edit' or 'delete this file'

**Comment by brunnerh** [comment]
On that note, hitting Escape probably should also cancel the name edit.
