### ISSUE TITLE
REPL: Add "Rollup Output"

### ISSUE THREAD

**Issue by Ocean-OS** [sveltejs/svelte.dev#794]
One of Svelte's best traits is the small bundle size. This size isn't really visible when using the REPL; there's a standard internal library, and it's hard to know just how big a component will be without compiling it yourself with Rollup or a similar tool. Because of this, I think it'd be best to add a "Rollup Output" tab to the REPL. This would not only show the actual code that would run on the client, but also how small it is.

**Comment by dummdidumm** [comment]
Not sure if this well help much. The final bundle size also needs to account for the runtime, and how big of an impact that makes depends on how many components you have. There's also treeshaking and minification.
Overall it would be a flawed approximation, therefore closing.
