### ISSUE TITLE
Breadcrumb and title are sticked together in docs

### ISSUE THREAD

**Issue by phamduylong** [sveltejs/svelte.dev#809]
Probably not intentional but the h1 here and breadcrumb content is sticked together (see cursor highlighted text). Can add a colon or something.

![image](https://github.com/user-attachments/assets/779a86f9-cf60-4458-8129-93a00d0fe3b5)

Browsed through the code and it happens [here](https://github.com/sveltejs/svelte.dev/blob/123a2b305376a0aaf8b9b3d2d776b6861657f954/apps/svelte.dev/src/routes/docs/%5B...path%5D/%2Bpage.svelte#L71). I can throw a PR quite quickly if the proposed solution is approved (separating them with a colon).

**Comment by Conduitry** [comment]
This was a styling issue caused by a bug in Svelte 5.1.10 with `:not()` selector handling. We've reverted to 5.1.9 for now (#810).
