### ISSUE TITLE
Full text in RSS feed

### ISSUE THREAD

**Issue by baukevanderlaan** [sveltejs/svelte.dev#837]
I'm grateful for the Svelte blog RSS feed, and would be even happier if the feed would serve the full text instead of only the summary. Anecdotally, a quick look in my RSS reader shows me that most blogs show the full text directly. Is this up for consideration? I'd gladly work on a PR and thought about the following options:

1. Show the full text in `https://svelte.dev/blog/rss.xml`, replacing the current style of showing only summaries.
2. Provide an additional feed accessible under a unique url: `https://svelte.dev/blog/rss-full.xml`
3. Provide an additional feed accessible with query params: `https://svelte.dev/blog/rss.xml?mode=full`

**Comment by Rich-Harris** [comment]
Related (but outdated): https://github.com/sveltejs/svelte/pull/9085
