### ISSUE TITLE
svelte.dev on IE

### ISSUE THREAD

**Issue by ghost** [sveltejs/svelte.dev#860]
The site could look better or it could display some message for IE is not supported. 

![Screenshot_1](https://user-images.githubusercontent.com/1254613/66823586-3f011080-ef4f-11e9-8afd-7dbb3543a618.png)

**Comment by brunnerh** [comment]
Wonder how high the probability is that someone would access the site using IE at this point.
Suspect that this can be closed.

**Comment by dummdidumm** [comment]
Agree
