### ISSUE TITLE
Vim mode - weird behavior

### ISSUE THREAD

**Issue by uglyreptile** [sveltejs/svelte.dev#896]
With tutorial when "next button" is pressed vim mode resets (only reload helps). In playground when created a new component also resets in the original and new one.

**Comment by heygwangjin** [comment]
I want to try to fix this issue so I looked through the code. But this is tough to fix for me.
Any advice or guide on how to solve this bug?

**Comment by uglyreptile** [comment]
@Rich-Harris Maybe some UI and bug fix will be good to put into "Advent of Svelte")

**Comment by Rich-Harris** [comment]
#1049 🙂
