### ISSUE TITLE
Svelte Playground doesn't work in Safari 17 or lower

### ISSUE THREAD

**Issue by kevinrenskers** [sveltejs/svelte.dev#911]
The Svelte Playground doesn't work in Safari except for Safari 18. This is a pretty big problem as I rely on the Playground to test components and their CSS in older browsers (using browserstack.com).

This is Safari 12:

![Screenshot 2024-12-02 at 14 42 53](https://github.com/user-attachments/assets/f6cb3c03-1ccb-49d0-b964-c7d8098f5a6c)

Safari 13 and 14:

![Screenshot 2024-12-02 at 14 40 37](https://github.com/user-attachments/assets/ac0e505e-c151-42d6-95c3-ee3615a1b2a3)

Safari 15 and 16 and 17: it looks good but it never stops loading the compiler:

![Screenshot 2024-12-02 at 14 42 07](https://github.com/user-attachments/assets/0f1c7343-0484-4c7a-a1f2-84d7917184ae)

Only in Safari 18 does it work as expected:

![Screenshot 2024-12-02 at 14 46 50](https://github.com/user-attachments/assets/5ad8e56e-fb9d-4bc3-9321-80fffca9e928)

**Comment by dummdidumm** [comment]
anything in devtools that gives a hint (I don't have access to Safari)? Like, is this just a missing polyfill?
