### ISSUE TITLE
svelte playground is not loading if version is not given as a query parameter

### ISSUE THREAD

**Issue by sukeshpabolu** [sveltejs/svelte.dev#961]
This works: https://svelte.dev/playground/hello-world?version=5.9.0

This is not working: https://svelte.dev/playground/hello-world

**Comment by brunnerh** [comment]
If it _isn't_ working, that's probably just unpkg.com being unreliable.
This should work and is working for me, it will add the latest version automatically.

**Comment by dominikg** [comment]
works for me too, if the issue comes up again please share details (console&network tabs)
