### ISSUE TITLE
Front page has responsive issue

### ISSUE THREAD

**Issue by theetrain** [sveltejs/svelte.dev#982]
I noticed on Chrome and Brave for Android; the home page has some elements that are too wide. 

![Screenshot_20241210-235243.png](https://github.com/user-attachments/assets/129acd0b-a435-4f55-967c-407f51ae197e)

![Screenshot_20241210-235238.png](https://github.com/user-attachments/assets/dc60559c-c14d-406c-83ec-93f8c7b41274)

**Comment by kresnasatya** [comment]
The culprit is from commit d6a64f82bef4e1fc6226390698d63722613e746c. Looks like we need to tweak styles in after update version of `@sveltejs/enhange-img`.

**Comment by kresnasatya** [comment]
In `<Testimonials>` component, it use `<enhanced:img>` html tags. If I try to remove the 

```html 
<enhanced:img
			class="pronunciation"
			alt="Svelte pronunciation guide"
			src="./svelte-pronunciation.svg"
		/>
```

The responsive issue is out. Looks like we need to set width and height for svg. Hmm..

**Comment by kresnasatya** [comment]
It's fixed now. Feel free to check and don't forget to close this issue to reduce maintainer burden. :)

**Comment by theetrain** [comment]
Thank you!
